const FILTER_PARAM='filter';
const PAGE_PARAM='page';
const PAGE_SIZE_PARAM='pageSize';
const SORT_PARAM='sort';
const SORT_ASCENDING='asc';
const SORT_DESCENDING='desc';

export { FILTER_PARAM, PAGE_PARAM, PAGE_SIZE_PARAM, SORT_PARAM, SORT_ASCENDING, SORT_DESCENDING };